# Generated by Django 4.0.4 on 2022-06-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_course_sondageglob_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
