# Generated by Django 4.0.4 on 2022-06-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_question_answer_remove_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='question_number',
        ),
    ]
