# Generated by Django 4.0.4 on 2022-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_course_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
