# Generated by Django 4.0.4 on 2022-06-28 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_question_option_four_count_question_option_one_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_four_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_two_count',
        ),
        migrations.AddField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
