# Generated by Django 4.0.4 on 2022-06-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_question_option_four_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
